title: Twitter Movement Derivation
email: jennings.anderson@colorado.edu
description: >
  CHIME
baseurl: "/Twitter-Movement-Derivation" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: jenningsatcu
github_username:  jenningsanderson

# Build settings
markdown: kramdown
